default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: orion_development
  host: localhost
  username: orion

test:
  <<: *default
  database: orion_test
  host: localhost
  username: orion
  password:

staging:
  <<: *default
  database: orion_staging
  host: localhost
  username: orion
  password:

production:
  <<: *default
  database: orion_production
  host: localhost
  username: orion
  password:
